<a href="https://colab.research.google.com/github/ipark2/test_project/blob/main/lesson_01_contents_orientation_%26_numpy_1_array%2C_zero%2C_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 목차
    - numpy
    - pandas
    - matplotlib & seaborn
    - scikit-learn

### Numpy
    - 행렬 연산을 가능하게 해주는 패키지
    - python으로 작성되나 연산은 C, C++, 포트란으로 진행
        - 선형대수 연산을 빠르게 할 수 있음

In [4]:
import numpy as np # 넘파이 라이브러리 불러오기, 및 np로 작성시 넘파이 사용약속
arr       = np.array([1, 2, 3]), dtype='int32'
type(arr), arr

SyntaxError: ignored

    - ndarray : 한가지 데이터 타입만으로 사용이 가능

In [5]:
from numpy.core.fromnumeric import size
a=np.random.randint(2,10,size=(5,))
b=np.random.randint(2,10,size=(2,4))
c=np.random.randint(2,10,size=(2,4))
c=np.random.randint(2,10,size=(2,4))


NameError: ignored

In [6]:
arrarr2.reshape(3, 2)

NameError: ignored

In [7]:
arr2[1]

NameError: ignored

In [8]:
ls = [1, 2, 3]
ls[1] = 5
ls

[1, 5, 3]

#### 데이터 수정

In [ ]:
ls = [1, 2, 3]
ls[1] = 5
ls

[1, 5, 3]

In [9]:
arr3 = np.array([[1, 2, 3],
                 [0, 1, 0]])
arr3[1][1] = 0
arr3

array([[1, 2, 3],
       [0, 0, 0]])

##### array 브로드캐스팅

In [10]:
arr3[0] = 5
arr3[1] = [5, 6, 7]
arr3

array([[5, 5, 5],
       [5, 6, 7]])

##### array 조건 선택

In [12]:
arr3[0] = 5
arr3[1] = [5, 6, 7]
arr3

array([[5, 5, 5],
       [5, 6, 7]])

In [13]:
idx = arr3>5
idx

array([[False, False, False],
       [False,  True,  True]])

In [16]:
arr3[arr3>5]

array([6, 7])

##### 조건에 맞는 값만 변경

In [ ]:
arr3[idx] = 100
arr3

#### zero array

In [ ]:
zero_arr = np.zeros(shape =(2, 3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
type(zero_arr)

NameError: ignored

In [19]:
zero_arr.dtype # 실수형 값만 바꿔 넣을 수 있음

NameError: ignored

##### array안의 데이터 형태 변경

In [21]:
z2 = zero_arr.astype('int16')
z2.dtype

NameError: ignored

#### one array

In [23]:
one_arr = np.ones((2, 3))
one_arr.dtype, one_arr

(dtype('float64'), array([[1., 1., 1.],
        [1., 1., 1.]]))

In [25]:
one_arr2 = np.ones((2, 3, 2)).astype('int')
one_arr2.dtype, one_arr2

(dtype('int64'), array([[[1, 1],
         [1, 1],
         [1, 1]],
 
        [[1, 1],
         [1, 1],
         [1, 1]]]))

In [27]:
id = np.identity(n=9, dtype=np,int8)
id

SyntaxError: ignored

#### 범위값 array 생성

In [29]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])