<a href="https://colab.research.google.com/github/ipark2/test_project/blob/main/lesson_03_numpy_3_modules_statistics%2C_lin%2Clogspace%2C_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy modules

In [1]:
import numpy as np

ary = [26, 28, 30, 35, 27, 31, 44]
ary = np.array(ary)
ary

array([26, 28, 30, 35, 27, 31, 44])

In [2]:
import numpy as np

arr = np.random.randn(100)
arr

array([ 2.42394544, -0.69448006, -0.17882502, -0.01698895, -0.73799336,
        0.62846845, -1.04780167, -0.97322002, -0.38692323, -0.29759709,
       -0.41406012,  0.43706401,  0.08350642, -1.74266018,  0.1026655 ,
       -0.23245636, -0.07286976, -0.43284735,  2.26754418,  0.18403579,
       -1.59282777,  1.05950314, -0.67266407,  1.0891036 ,  0.60151808,
        0.6051742 , -0.86493856,  0.07011942,  0.56427413, -0.24783656,
       -0.56736297, -1.12047965, -1.06178879, -0.32794638, -1.77313667,
        0.00691536, -0.56052783, -0.71592155,  0.86617453,  0.9605173 ,
        1.13441187, -0.15112306,  1.10825889,  0.83310624, -0.49234695,
        0.38582997, -0.51583054, -0.72603329,  1.86819533, -2.70124185,
       -0.22620136, -0.27557784,  0.64369286, -0.0220598 , -0.70049256,
       -0.73915814,  2.06480456,  0.18251867,  1.94130257, -0.22329252,
       -1.25831786, -0.60450849,  1.55479477,  1.21804146,  0.28514647,
        0.21327649, -1.46303188, -1.08629219,  1.99344105,  0.10

#### Statistics modules
    - max, min, median, mean, std, var
    - cov, corrcoef

In [5]:
np.max(arr), np.min(arr), np.mean(arr), np.var(arr), np.std(arr) #최대 최소 평균 표준편차 

(2.423945441898959,
 -2.7012418489529324,
 -0.05364106276678861,
 1.10636021127734,
 1.051836589626611)

#### linspace, logspace
    - linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
    - logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [6]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

##### logspace
    - log10(x1)=2, log_10(x_2)=4

In [7]:
np.logspace(2, 4, 3)

array([  100.,  1000., 10000.])

##### 2000년 최저시급과 2019년 최저시급을 가정하여 선형적 증가 추세를 보고싶다면?

In [ ]:
time_00 = 1600
time_19 = 8350
np.linspace(time_00, time_19, 10)

array([1600., 2350., 3100., 3850., 4600., 5350., 6100., 6850., 7600.,
       8350.])

#### numpy random module
    - seed : 랜덤의 설정값
    - rand : 균등분포로 난수 생생
    - randn : 정규분포로 난수 생성
    - randint : 균등분포로 정수 생성
    - shuffle : 섞기
    - choice : 데이터를 특정 확률로 뽑기

##### seed

In [8]:
np.random.seed(1)  # arbitrary 
res1 = np.random.randint(10, 100, 10)

np.random.seed(2)
res2 = np.random.randint(10, 100, 10)

np.random.seed(1)
res3 = np.random.randint(10, 100, 10)

res1, res2, res3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]))

##### rand

In [9]:
np.random.rand(10)

array([0.18626021, 0.34556073, 0.39676747, 0.53881673, 0.41919451,
       0.6852195 , 0.20445225, 0.87811744, 0.02738759, 0.67046751])

In [ ]:
np.random.rand(10)

array([0.4173048 , 0.55868983, 0.14038694, 0.19810149, 0.80074457,
       0.96826158, 0.31342418, 0.69232262, 0.87638915, 0.89460666])

In [ ]:
np.random.rand(10)

array([0.41919451, 0.6852195 , 0.20445225, 0.87811744, 0.02738759,
       0.67046751, 0.4173048 , 0.55868983, 0.14038694, 0.19810149])

##### randn

In [10]:
np.random.randn(10)

array([ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
       -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521])

Numpy method


*   all: 모든 값이 True일 때 True 반환
*   any: 값이 하나라도 True일 때 True 반환
*   argmax : axis를 기준으로 최대값의 index를 반환
*   argmin : axis를 기준으로 최소값의 index를 반환
*   argsort : 값의 크기순으로 index를 반환
*   np.where: 조건에 맞는 값을 반환

In [11]:
arr = np.random.randint(0,10,(3,3))
arr

array([[4, 8, 1],
       [4, 0, 3],
       [9, 2, 0]])

In [12]:
np.any(arr > 5)

# np.all(arr > 5)

# np.all(arr < 10)

# np.argmin(arr. axis=0)

# np.argmax(arr, 1)

# np.argsort(arr, axis=0)

# arr[np.where(arr>5)]

# np.where(arr<5, 10, arr)

True

In [13]:
arr = np.random.randint(0,10,(4,4))
arr

array([[4, 9, 2, 7],
       [7, 9, 8, 6],
       [9, 3, 7, 7],
       [4, 5, 9, 3]])

In [14]:
np.max(arr, axis=1)

# np.mean(arr, 0)

# np.min(arr, 1)

# np.std(arr), np.std(arr, 0)

# np.sum(arr)

array([9, 9, 9, 9])

In [15]:
arr = np.random.randint(0,10,(2,4))
arr

array([[6, 8, 0, 2],
       [7, 7, 9, 7]])

In [20]:
arr1 = arr[..., np.newaxis]
arr1.shape
arr2 = np.squeeze(arr1, -1)
arr2.shape
arr3 = np.transpose(arr1, (2,1,0))
arr3.shape, arr1.shape
# arr4 = arr1.reshape(1,4,2)

# arr5 = arr2.T

((1, 4, 2), (2, 4, 1))

##### randint

In [ ]:
x = np.random.randint(1, 10, (4, 4))
x

array([[7, 7, 1, 1],
       [3, 7, 1, 7],
       [8, 1, 4, 1],
       [4, 5, 8, 6]])

In [ ]:
np.random.shuffle(x)
x

array([[4, 5, 8, 6],
       [3, 7, 1, 7],
       [7, 7, 1, 1],
       [8, 1, 4, 1]])