<a href="https://colab.research.google.com/github/ipark2/test_project/blob/main/lesson_01_python_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 환경구성
    Anaconda 환경
    jupyter notebook

### Jupyter notebook 
    mode
        - 명령모드(esc)
        - 편집모드(셀 선택 후 enter)

    Style
        - markdown
        - code

이곳에는 노트를 작성하실 수 있습니다

    - 1순위
        - 2순위
            - 3순위

In [ ]:
python code

    
    단축키
        - shift+enter : 아래 셀로 내려가면서 실행
        - ctrl+enter : 현재 셀에 머무르면서 실행      
        - dd(명령모드) : 셀 삭제
        - a : 현재 선택된 셀 위에 새로운 셀 생성
        - b : 현재 선택된 셀 아래에 새로운 셀 생성
        - spacebar : 현재 화면을 위로 올림

#### magic command
    - % : 한 줄의 magic command를 동작
    - %% : 셀 단위의 magic command를 동작
    - 주요 magic command
        %pwd : 현재 jupyter notebook 파일의 경로
        %ls : 현재 디렉토리의 파일 리스트 출력
        %whos : 현재 선언된 변수들을 출력
        %reset : 현재 선언된 변수들을 전부 삭제

In [ ]:
%pwd

'/content'

#### shell command
    - jupyter notebook을 실행한 shell 환경의 명령을 사용
    - 명령어 앞에 !를 붙여서 실행    

In [ ]:
!pip install SimpleITK

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 48.4 MB 2.8 MB/s 


### 기본 문법
    - 변수 선언, 식별자, 자료형, 형변환, 연산자

#### 주석과 출력
    - 주석 : 작성한 문장 맨 앞에 #을 붙이면 주석처리
    - 출력 : 셀의 마지막 문장 하나만 결과로 출력
            여러 결과나 코드 중간 변수 값을 출력하고 싶을때 print(출력물)로 작성

In [ ]:
print('Hello Python')
# print ('안녕 파이썬')


Hello Python


In [ ]:
a = 20
b = 30
a + b

50

In [ ]:
print("출력 예제 입니다")

출력 예제 입니다


In [ ]:
a = 10
b = 20
# print(a+b)
a + b

30

In [ ]:
"""이 안에 설명을 쓰시면 됩니다."""

'이 안에 설명을 쓰시면 됩니다.'

In [ ]:
for i in range(1, 11):
    print('안녕하세요')

안녕하세요
안녕하세요
안녕하세요
안녕하세요
안녕하세요
안녕하세요
안녕하세요
안녕하세요
안녕하세요
안녕하세요


    - docstring : 함수의 사용법을 설명 (단축키: shift+tab)
    - 자동완성 : 코드의 일부분만 작성하고 뒷부분을 자동으로 채워주는 기능 (단축키: tab)

In [ ]:
import random # random 라이브러리를 불러오는 것
random.randint
random.random

<function Random.random>

In [ ]:
random.randint, random.random

#### 변수 선언
    RAM 저장 공간에 값을 할당하는 행위

In [ ]:
a = 10
b = 20
c = a+b
print(c)

30


In [ ]:
d, e = 3, 4
f = g = 5
print(d, e, f, g)

3 4 5 5


In [ ]:
g = h = 70
g, h

(70, 70)

In [ ]:
import numpy as np # numpy 라이브러리를 불러옴
a = np.random.randint(0,10,(10,10)) #행렬의 크기가 10x10이고 값들은 0부터 9까지

b = np.random.randint(11,20,(10,10))
print(a, "\n",b,"\n", a+b)


[[3 6 9 4 1 6 6 4 4 1]
 [0 7 2 7 0 9 3 0 9 1]
 [9 1 7 6 4 8 9 7 4 3]
 [3 6 5 1 7 4 4 9 8 4]
 [1 8 7 7 6 4 7 5 3 7]
 [8 8 4 7 9 6 2 4 3 0]
 [7 5 7 3 4 1 8 8 0 5]
 [5 9 8 4 3 4 9 6 5 0]
 [6 9 9 5 2 1 2 7 7 4]
 [3 8 2 0 8 0 3 1 2 9]] 
 [[11 12 19 13 16 12 15 19 11 19]
 [15 11 11 19 19 11 18 14 12 13]
 [12 18 18 16 19 15 19 11 18 17]
 [12 19 18 14 16 15 17 16 17 15]
 [11 13 13 11 14 18 17 16 13 12]
 [12 18 14 17 17 12 15 15 15 16]
 [18 15 19 13 14 12 16 19 11 13]
 [17 12 19 13 11 15 13 12 18 16]
 [18 18 13 16 18 16 12 19 18 15]
 [12 18 12 19 17 12 14 12 17 17]] 
 [[14 18 28 17 17 18 21 23 15 20]
 [15 18 13 26 19 20 21 14 21 14]
 [21 19 25 22 23 23 28 18 22 20]
 [15 25 23 15 23 19 21 25 25 19]
 [12 21 20 18 20 22 24 21 16 19]
 [20 26 18 24 26 18 17 19 18 16]
 [25 20 26 16 18 13 24 27 11 18]
 [22 21 27 17 14 19 22 18 23 16]
 [24 27 22 21 20 17 14 26 25 19]
 [15 26 14 19 25 12 17 13 19 26]]


#### 식별자
    - 변수, 함수, 클래스, 모듈 등의 이름
    - 규칙
        - 소문자, 대문자, 숫자, _ (low dash / under_score)
        - 가장 앞에 숫자 사용 불가
        - 예약어 사용 불가 (def, class, int, ...) : 이미 python에서 문법적으로 정의되어 있는 식별자
        - Convention
            - snake_case : 변수, 함수
            - CamelCase : class

In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
candy_bar
LowDashError

NameError: ignored

#### 데이터 타입
    - RAM 저장 공간을 효율적으로 사용하기 위해서 저장 공간의 타입 설정
    - 동적 타이핑
        - 변수 선언 시 저장되는 값에 따라서 자동으로 타입이 설정

In [ ]:
%whos

In [ ]:
%reset

In [ ]:
%whos

Interactive namespace is empty.


In [ ]:
a = 1
b = 'python'
c = 1.0
type(a), type(b), type(c)

In [ ]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
