<a href="https://colab.research.google.com/github/ipark2/test_project/blob/main/lesson_04_numpy_4_vector_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### inner product

In [4]:
import numpy as np
a = np.random.randint(0,10,(2,4))
b = np.random.randint(0,10,(2,4))
a,b


(array([[0, 6, 8, 2],
        [3, 6, 9, 3]]), array([[6, 7, 0, 9],
        [9, 3, 8, 4]]))

In [3]:
np.dot(a,b.T)

array([[34, 40],
       [45, 76]])

In [ ]:
np.inner(a,b)

array([[84, 16],
       [70, 29]])

 - numpy.inner : 1차원 또는 2차원 배열일 경우 내적을 위해 두 번째 행렬을 전치한 다음 곱해준다.
 - numpy.dot : 2차원 배열의 경우 행렬곱 연산을 수행하며 1차원 배열일 경우 벡터의 내적에 해당한다. 

In [ ]:
# blank

### 고유값, 고유벡터

In [ ]:
# blank

In [ ]:
# blank

(array([1.+1.j, 1.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))