<a href="https://colab.research.google.com/github/ipark2/test_project/blob/main/lesson_01_contents_orientation_%26_numpy_1_array%2C_zero%2C_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 목차
    - numpy
    - pandas
    - matplotlib & seaborn
    - scikit-learn

### Numpy
    - 행렬 연산을 가능하게 해주는 패키지
    - python으로 작성되나 연산은 C, C++, 포트란으로 진행
        - 선형대수 연산을 빠르게 할 수 있음

In [2]:
import numpy as np # 넘파이 라이브러리 불러오기, 및 np로 작성시 넘파이 사용약속
arr = np.array([1, 2, 3]). dtype='int32'
type(arr), arr

(str, 'int32')

    - ndarray : 한가지 데이터 타입만으로 사용이 가능

In [6]:
arr2 = np.array([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0]])
print(arr2)         # 행렬 확인
print(arr2.ndim)    # 형렬의 차원
print(arr2.shape)   # 행렬의 형태
print(arr2.size)    # 형렬 내 원소개수
print(arr2.dtype)   # 행렬의 자료형


ary2, ary2.ndim, ary2.shape

[[1. 2. 3.]
 [4. 5. 6.]]
2
(2, 3)
6
float64


(array([[1., 2., 3.],
        [4., 5., 6.]]), 2, (2, 3))

In [7]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [8]:
a=np.random.randint(2,10,size=(5,))
b=np.random.randint(2,10,size=(2,4))
c=np.random.randint(2,10,size=(2,3,4))
print(a)
print(b)
print(c)

[6 4 6 5 9]
[[7 8 9 2]
 [9 4 5 6]]
[[[8 8 3 8]
  [3 7 4 7]
  [3 5 4 5]]

 [[5 6 7 7]
  [2 6 5 7]
  [4 2 8 2]]]


In [9]:
arr2.reshape(3, 2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [10]:
arr2[1]

array([4., 5., 6.])

In [11]:
arr2[1, 1]

5.0

#### 데이터 수정

In [12]:
ls = [1, 2, 3]
ls[1] = 5
ls

[1, 5, 3]

In [13]:
arr3 = np.array([[1, 2, 3],
                 [0, 1, 0]])
arr3[1][1] = 0
arr3

array([[1, 2, 3],
       [0, 0, 0]])

##### array 브로드캐스팅

In [ ]:
ary3[0] = 0
ary3

array([[0, 0, 0],
       [0, 0, 0]])

##### array 조건 선택

In [14]:
arr3[0] = 5
arr3[1] = [5, 6, 7]
arr3

array([[5, 5, 5],
       [5, 6, 7]])

In [15]:
idx = arr3>5
idx

array([[False, False, False],
       [False,  True,  True]])

In [16]:
arr3[arr3>5]

array([6, 7])

##### 조건에 맞는 값만 변경

In [17]:
arr3[idx] = 100
arr3

array([[  5,   5,   5],
       [  5, 100, 100]])

#### zero array

In [18]:
zero_arr = np.zeros((2, 3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
type(zero_arr)

numpy.ndarray

In [20]:
zero_arr.dtype # 실수형 값만 바꿔 넣을 수 있음

dtype('float64')

##### array안의 데이터 형태 변경

In [22]:
z2 = zero_arr.astype('int16')
z2.dtype

dtype('int16')

#### one array

In [23]:
one_arr = np.ones((2, 3))
one_arr.dtype, one_arr

(dtype('float64'), array([[1., 1., 1.],
        [1., 1., 1.]]))

In [25]:
one_arr2 = np.ones((2, 3, 2)).astype('int')
one_arr2.dtype, one_arr2

(dtype('int64'), array([[[1, 1],
         [1, 1],
         [1, 1]],
 
        [[1, 1],
         [1, 1],
         [1, 1]]]))

In [29]:
id = np.identity(n=6, dtype=np.int8) # 단위 행렬
id

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int8)

#### 범위값 array 생성

In [33]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])